### ISSUE TITLE
[Gui bug] User should not see ruby code on article page

### ISSUE THREAD

**Issue by NataliaVolik** [rails-up/foodsharing#33]
![bug](http://image.prntscr.com/image/b1d4ac62d41d441ea5261a6914209c4c.png)

**Comment by dshramko** [comment]
It's not a bug, it's a feature.
You can see it only in development environment. so user won't see this text.
[see here](https://github.com/rails-up/foodsharing/blob/master/app/views/layouts/application.html.slim#L13)

**Comment by Khovanov** [comment]
Hi,
Because, you run project in development mode.
